# ---MLP QR-DQN Networks---
actor_network:
  pre_torso:
    _target_: stoix.networks.torso.MLPTorso
    layer_sizes: [256, 256] # Sizes of the layers in the torso.
    use_layer_norm: False
    activation: silu
  action_head:
    _target_: stoix.networks.heads.UtilityQuantileDiscreteQNetwork
    num_quantiles: ${system.num_quantiles}
