# ---Environment Configs---
env_name: gymnax_s # Used for logging purposes and selection of the corresponding wrapper.

scenario:
  name: GridWorld-v0
  task_name: stockgridworld # For logging purposes.

kwargs: {}

skwargs: {
  initial_stock: -5, # Initial stock of the agent.
  initial_stock_min: -10, # Initial stock of the agent.
  initial_stock_max: 10, # Initial stock of the agent.
}

# Defines the metric that will be used to evaluate the performance of the agent.
# This metric is returned at the end of an experiment and can be used for hyperparameter tuning.
eval_metric: episode_discounted_return

# optional - defines the threshold that needs to be reached in order to consider the environment solved.
# if present then solve rate will be logged.
#solved_return_threshold: 500.0
